# Generated by Django 2.0.2 on 2018-02-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balloon_time', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clown',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
