# Generated by Django 2.0.2 on 2018-02-14 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balloon_time', '0002_auto_20180213_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='party_date',
        ),
    ]
